openapi: 3.0.3
info:
  title: DoeAqui API
  description: API atômica para o sistema de doação de sangue DoeAqui.
  version: 1.0.0

servers:
  - url: http://localhost:8080/v1

paths:
  /usuario:
    post:
      summary: Insere um novo usuário
      operationId: postNewUser
      tags:
        - Usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUsuarioRequest'
      responses:
        '201':
          description: Usuário cadastrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioResponse'
        '400':
          description: Requisição inválida
        '500':
          description: Erro no servidor

  /login:
    post:
      summary: Obtém token JWT de autenticação
      operationId: postLoginCredentials
      tags:
        - Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Requisição inválida
        '500':
          description: Erro no servidor

  /tipoSanguineo:
    get:
      summary: Obter tipos sanguíneos
      operationId: getTiposSanguineos
      tags:
        - Tipo Sanguíneo
      responses:
        '200':
          description: Tipos sanguíneos obtidos com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TipoSanguineoResponse'
        '400':
          description: Requisição inválida
        '500':
          description: Erro no servidor

components:
  schemas:
    NewUsuarioRequest:
      type: object
      required:
        - nome
        - dataNascimento
        - cpf
        - genero
        - idTipoSanguineo
        - idPapel
        - login
      properties:
        nome:
          type: string
          minLength: 1
          maxLength: 150
        dataNascimento:
          type: string
          format: date
        cpf:
          type: string
          minLength: 11
          maxLength: 11
          pattern: '^[0-9]{11}$'
        genero:
          type: string
          minLength: 1
          maxLength: 1
        telefone:
          type: string
          maxLength: 20
        idTipoSanguineo:
          type: integer
          format: int32
        idPapel:
          type: integer
          format: int32
        login:
          $ref: '#/components/schemas/NewLoginRequest'

    NewLoginRequest:
      type: object
      required:
        - email
        - senha
      properties:
        email:
          type: string
          format: email
          maxLength: 100
        senha:
          type: string
          format: password
          minLength: 8
          maxLength: 100

    UsuarioResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nome:
          type: string
        dataNascimento:
          type: string
          format: date
        cpf:
          type: string
        genero:
          type: string
        email:
          type: string
          format: email
        telefone:
          type: string
        idTipoSanguineo:
          type: integer
          format: int32
        idPapel:
          type: integer
          format: int32
        ativo:
          type: boolean

    LoginRequest:
      type: object
      required:
        - email
        - senha
      properties:
        email:
          type: string
          format: email
          maxLength: 100
        senha:
          type: string

    LoginResponse:
      type: object
      required:
        - token
        - expirationTime
      properties:
        token:
          type: string
        expirationTime:
          type: string
          format: date-time

    TipoSanguineoResponse:
      type: object
      properties:
        id:
          type: string
        tipo:
          type: string
        fator:
          type: string